from app.services.api_service_arduino import ApiServiceArduino, api_service_arduino
from app.services.climate_record_service import ClimateRecordService, climate_record_service
from app.services.email_send_gmail import EmailSendGmail
from app.services.plain_transport import PlainTransport
from app.services.ssl_transport import SSLTransport
from app.services.tls_transport import TLSTransport